window.HACKEROS_TRANS_ARTICLES = {
  pl:{pageTitle:'HackerOS - Artykuły',h1:'Artykuły',intro:'Poradniki, przewodniki i teksty o HackerOS i jego narzędziach.',searchPlaceholder:'🔍 Szukaj artykułów…',allTags:'Wszystkie',minRead:'min czytania',back:'← Wszystkie artykuły',noResults:'Brak artykułów pasujących do wyszukiwania.',fallback:'Ten artykuł nie jest jeszcze dostępny w Twoim języku — wyświetlamy wersję angielską.',copy:'Kopiuj',copied:'Skopiowano!',toc:'Na tej stronie',loadError:'Nie udało się wczytać artykułu.',notFound:'Nie znaleziono takiego artykułu.',navArticles:'Artykuły'},
  en:{pageTitle:'HackerOS - Articles',h1:'Articles',intro:'Guides, walkthroughs and write-ups about HackerOS and its tools.',searchPlaceholder:'🔍 Search articles…',allTags:'All',minRead:'min read',back:'← All articles',noResults:'No articles match your search.',fallback:'',copy:'Copy',copied:'Copied!',toc:'On this page',loadError:'Could not load the article.',notFound:'That article does not exist.',navArticles:'Articles'},
  de:{pageTitle:'HackerOS - Artikel',h1:'Artikel',intro:'Anleitungen, Leitfäden und Beiträge rund um HackerOS und seine Werkzeuge.',searchPlaceholder:'🔍 Artikel suchen…',allTags:'Alle',minRead:'Min. Lesezeit',back:'← Alle Artikel',noResults:'Keine Artikel gefunden.',fallback:'Dieser Artikel ist noch nicht in Ihrer Sprache verfügbar – es wird die englische Version angezeigt.',copy:'Kopieren',copied:'Kopiert!',toc:'Auf dieser Seite',loadError:'Der Artikel konnte nicht geladen werden.',notFound:'Dieser Artikel existiert nicht.',navArticles:'Artikel'},
  fr:{pageTitle:'HackerOS - Articles',h1:'Articles',intro:'Guides, tutoriels et textes sur HackerOS et ses outils.',searchPlaceholder:'🔍 Rechercher des articles…',allTags:'Tous',minRead:'min de lecture',back:'← Tous les articles',noResults:'Aucun article ne correspond à votre recherche.',fallback:'Cet article n’est pas encore disponible dans votre langue — la version anglaise est affichée.',copy:'Copier',copied:'Copié !',toc:'Sur cette page',loadError:'Impossible de charger l’article.',notFound:'Cet article n’existe pas.',navArticles:'Articles'},
  es:{pageTitle:'HackerOS - Artículos',h1:'Artículos',intro:'Guías, tutoriales y textos sobre HackerOS y sus herramientas.',searchPlaceholder:'🔍 Buscar artículos…',allTags:'Todos',minRead:'min de lectura',back:'← Todos los artículos',noResults:'Ningún artículo coincide con tu búsqueda.',fallback:'Este artículo aún no está disponible en tu idioma: se muestra la versión en inglés.',copy:'Copiar',copied:'¡Copiado!',toc:'En esta página',loadError:'No se pudo cargar el artículo.',notFound:'Ese artículo no existe.',navArticles:'Artículos'},
  it:{pageTitle:'HackerOS - Articoli',h1:'Articoli',intro:'Guide, tutorial e approfondimenti su HackerOS e i suoi strumenti.',searchPlaceholder:'🔍 Cerca articoli…',allTags:'Tutti',minRead:'min di lettura',back:'← Tutti gli articoli',noResults:'Nessun articolo corrisponde alla ricerca.',fallback:'Questo articolo non è ancora disponibile nella tua lingua: viene mostrata la versione inglese.',copy:'Copia',copied:'Copiato!',toc:'In questa pagina',loadError:'Impossibile caricare l’articolo.',notFound:'Questo articolo non esiste.',navArticles:'Articoli'},
  ru:{pageTitle:'HackerOS - Статьи',h1:'Статьи',intro:'Руководства, обзоры и материалы о HackerOS и его инструментах.',searchPlaceholder:'🔍 Поиск статей…',allTags:'Все',minRead:'мин чтения',back:'← Все статьи',noResults:'Статей по вашему запросу не найдено.',fallback:'Эта статья пока недоступна на вашем языке — показана английская версия.',copy:'Копировать',copied:'Скопировано!',toc:'На этой странице',loadError:'Не удалось загрузить статью.',notFound:'Такой статьи нет.',navArticles:'Статьи'},
  uk:{pageTitle:'HackerOS - Статті',h1:'Статті',intro:'Посібники, огляди та матеріали про HackerOS і його інструменти.',searchPlaceholder:'🔍 Пошук статей…',allTags:'Усі',minRead:'хв читання',back:'← Усі статті',noResults:'Статей за вашим запитом не знайдено.',fallback:'Ця стаття поки недоступна вашою мовою — показано англійську версію.',copy:'Копіювати',copied:'Скопійовано!',toc:'На цій сторінці',loadError:'Не вдалося завантажити статтю.',notFound:'Такої статті немає.',navArticles:'Статті'},
  zh:{pageTitle:'HackerOS - 文章',h1:'文章',intro:'关于 HackerOS 及其工具的指南、教程和文章。',searchPlaceholder:'🔍 搜索文章…',allTags:'全部',minRead:'分钟阅读',back:'← 所有文章',noResults:'没有符合搜索条件的文章。',fallback:'此文章暂无您所用语言的版本——正在显示英文版。',copy:'复制',copied:'已复制！',toc:'本页内容',loadError:'无法加载文章。',notFound:'该文章不存在。',navArticles:'文章'},
  ja:{pageTitle:'HackerOS - 記事',h1:'記事',intro:'HackerOS とそのツールに関するガイドや解説記事。',searchPlaceholder:'🔍 記事を検索…',allTags:'すべて',minRead:'分で読めます',back:'← すべての記事',noResults:'検索に一致する記事はありません。',fallback:'この記事はまだお使いの言語では利用できません。英語版を表示しています。',copy:'コピー',copied:'コピーしました！',toc:'このページの内容',loadError:'記事を読み込めませんでした。',notFound:'その記事は存在しません。',navArticles:'記事'}
};
