window.HACKEROS_TRANS_DOWNLOAD = {
    pl:{pageTitle:'HackerOS - Download',sectionH1:'Pobierz HackerOS',quickTitle:'Szybkie pobieranie systemu',quickDesc:'Wybierz edycję HackerOS i pobierz bezpośrednio z SourceForge.',selectLabel:'Wybierz edycję:',selectDefault:'-- Wybierz edycję --',downloadBtn:'Pobierz',btnSourceForge:'Pobierz z SourceForge',btnMega:'Pobierz z Mega.nz',btnDrive:'Pobierz z Google Drive',btnTransfer:'Pobierz z Transfer.it',footerCopy:'© 2026 HackerOS. Wszelkie prawa zastrzeżone.',navHome:'Home',navDownload:'Download',navReleases:'Releases',navTeam:'HackerOS Team',navDocs:'Documentation'},
    en:{pageTitle:'HackerOS - Download',sectionH1:'Download HackerOS',quickTitle:'Quick System Download',quickDesc:'Select the HackerOS edition and download directly from SourceForge.',selectLabel:'Select edition:',selectDefault:'-- Select edition --',downloadBtn:'Download',btnSourceForge:'Download from SourceForge',btnMega:'Download from Mega.nz',btnDrive:'Download from Google Drive',btnTransfer:'Download from Transfer.it',footerCopy:'© 2026 HackerOS. All rights reserved.',navHome:'Home',navDownload:'Download',navReleases:'Releases',navTeam:'HackerOS Team',navDocs:'Documentation'},
    de:{pageTitle:'HackerOS - Download',sectionH1:'HackerOS herunterladen',quickTitle:'Schneller System-Download',quickDesc:'Wähle die HackerOS-Edition und lade direkt von SourceForge herunter.',selectLabel:'Edition wählen:',selectDefault:'-- Edition wählen --',downloadBtn:'Herunterladen',btnSourceForge:'Von SourceForge herunterladen',btnMega:'Von Mega.nz herunterladen',btnDrive:'Von Google Drive herunterladen',btnTransfer:'Von Transfer.it herunterladen',footerCopy:'© 2026 HackerOS. Alle Rechte vorbehalten.',navHome:'Home',navDownload:'Download',navReleases:'Releases',navTeam:'HackerOS Team',navDocs:'Dokumentation'},
    fr:{pageTitle:'HackerOS - Téléchargement',sectionH1:'Télécharger HackerOS',quickTitle:'Téléchargement rapide',quickDesc:'Sélectionnez l\'édition HackerOS et téléchargez directement depuis SourceForge.',selectLabel:'Sélectionner l\'édition :',selectDefault:'-- Sélectionner l\'édition --',downloadBtn:'Télécharger',btnSourceForge:'Télécharger depuis SourceForge',btnMega:'Télécharger depuis Mega.nz',btnDrive:'Télécharger depuis Google Drive',btnTransfer:'Télécharger depuis Transfer.it',footerCopy:'© 2026 HackerOS. Tous droits réservés.',navHome:'Accueil',navDownload:'Télécharger',navReleases:'Versions',navTeam:'Équipe HackerOS',navDocs:'Documentation'},
    es:{pageTitle:'HackerOS - Descargar',sectionH1:'Descargar HackerOS',quickTitle:'Descarga rápida del sistema',quickDesc:'Selecciona la edición de HackerOS y descarga directamente desde SourceForge.',selectLabel:'Seleccionar edición:',selectDefault:'-- Seleccionar edición --',downloadBtn:'Descargar',btnSourceForge:'Descargar desde SourceForge',btnMega:'Descargar desde Mega.nz',btnDrive:'Descargar desde Google Drive',btnTransfer:'Descargar desde Transfer.it',footerCopy:'© 2026 HackerOS. Todos los derechos reservados.',navHome:'Inicio',navDownload:'Descargar',navReleases:'Versiones',navTeam:'Equipo HackerOS',navDocs:'Documentación'},
    it:{pageTitle:'HackerOS - Download',sectionH1:'Scarica HackerOS',quickTitle:'Download rapido del sistema',quickDesc:"Seleziona l'edizione di HackerOS e scarica direttamente da SourceForge.",selectLabel:"Seleziona edizione:",selectDefault:"-- Seleziona edizione --",downloadBtn:'Scarica',btnSourceForge:'Scarica da SourceForge',btnMega:'Scarica da Mega.nz',btnDrive:'Scarica da Google Drive',btnTransfer:'Scarica da Transfer.it',footerCopy:'© 2026 HackerOS. Tutti i diritti riservati.',navHome:'Home',navDownload:'Download',navReleases:'Versioni',navTeam:'Team HackerOS',navDocs:'Documentazione'},
    ru:{pageTitle:'HackerOS - Скачать',sectionH1:'Скачать HackerOS',quickTitle:'Быстрая загрузка системы',quickDesc:'Выберите редакцию HackerOS и загрузите напрямую с SourceForge.',selectLabel:'Выберите редакцию:',selectDefault:'-- Выберите редакцию --',downloadBtn:'Скачать',btnSourceForge:'Скачать с SourceForge',btnMega:'Скачать с Mega.nz',btnDrive:'Скачать с Google Drive',btnTransfer:'Скачать с Transfer.it',footerCopy:'© 2026 HackerOS. Все права защищены.',navHome:'Главная',navDownload:'Скачать',navReleases:'Релизы',navTeam:'Команда HackerOS',navDocs:'Документация'},
    uk:{pageTitle:'HackerOS - Завантажити',sectionH1:'Завантажити HackerOS',quickTitle:'Швидке завантаження системи',quickDesc:'Оберіть редакцію HackerOS і завантажте безпосередньо з SourceForge.',selectLabel:'Оберіть редакцію:',selectDefault:'-- Оберіть редакцію --',downloadBtn:'Завантажити',btnSourceForge:'Завантажити з SourceForge',btnMega:'Завантажити з Mega.nz',btnDrive:'Завантажити з Google Drive',btnTransfer:'Завантажити з Transfer.it',footerCopy:'© 2026 HackerOS. Усі права захищені.',navHome:'Головна',navDownload:'Завантажити',navReleases:'Релізи',navTeam:'Команда HackerOS',navDocs:'Документація'},
    zh:{pageTitle:'HackerOS - 下载',sectionH1:'下载 HackerOS',quickTitle:'快速下载系统',quickDesc:'选择 HackerOS 版本并直接从 SourceForge 下载。',selectLabel:'选择版本：',selectDefault:'-- 选择版本 --',downloadBtn:'下载',btnSourceForge:'从 SourceForge 下载',btnMega:'从 Mega.nz 下载',btnDrive:'从 Google Drive 下载',btnTransfer:'从 Transfer.it 下载',footerCopy:'© 2026 HackerOS. 保留所有权利。',navHome:'主页',navDownload:'下载',navReleases:'版本',navTeam:'HackerOS 团队',navDocs:'文档'},
    ja:{pageTitle:'HackerOS - ダウンロード',sectionH1:'HackerOS をダウンロード',quickTitle:'クイックシステムダウンロード',quickDesc:'HackerOS のエディションを選択して SourceForge から直接ダウンロード。',selectLabel:'エディションを選択：',selectDefault:'-- エディションを選択 --',downloadBtn:'ダウンロード',btnSourceForge:'SourceForge からダウンロード',btnMega:'Mega.nz からダウンロード',btnDrive:'Google Drive からダウンロード',btnTransfer:'Transfer.it からダウンロード',footerCopy:'© 2026 HackerOS. 全著作権所有。',navHome:'ホーム',navDownload:'ダウンロード',navReleases:'リリース',navTeam:'HackerOS チーム',navDocs:'ドキュメント'},
};
