window.HACKEROS_TRANS_TEAM = {
    pl:{pageTitle:'HackerOS - Team',sectionH1:'Zespół HackerOS',member0Role:'Założyciel HackerOS',footerCopy:'© 2026 HackerOS. Wszelkie prawa zastrzeżone.',navHome:'Home',navDownload:'Download',navReleases:'Releases',navTeam:'HackerOS Team',navDocs:'Documentation'},
    en:{pageTitle:'HackerOS - Team',sectionH1:'HackerOS Team',member0Role:'Founder of HackerOS',footerCopy:'© 2026 HackerOS. All rights reserved.',navHome:'Home',navDownload:'Download',navReleases:'Releases',navTeam:'HackerOS Team',navDocs:'Documentation'},
    de:{pageTitle:'HackerOS - Team',sectionH1:'HackerOS Team',member0Role:'Gründer von HackerOS',footerCopy:'© 2026 HackerOS. Alle Rechte vorbehalten.',navHome:'Home',navDownload:'Download',navReleases:'Releases',navTeam:'HackerOS Team',navDocs:'Dokumentation'},
    fr:{pageTitle:'HackerOS - Équipe',sectionH1:'Équipe HackerOS',member0Role:'Fondateur de HackerOS',footerCopy:'© 2026 HackerOS. Tous droits réservés.',navHome:'Accueil',navDownload:'Télécharger',navReleases:'Versions',navTeam:'Équipe HackerOS',navDocs:'Documentation'},
    es:{pageTitle:'HackerOS - Equipo',sectionH1:'Equipo HackerOS',member0Role:'Fundador de HackerOS',footerCopy:'© 2026 HackerOS. Todos los derechos reservados.',navHome:'Inicio',navDownload:'Descargar',navReleases:'Versiones',navTeam:'Equipo HackerOS',navDocs:'Documentación'},
    it:{pageTitle:'HackerOS - Team',sectionH1:'Team HackerOS',member0Role:'Fondatore di HackerOS',footerCopy:'© 2026 HackerOS. Tutti i diritti riservati.',navHome:'Home',navDownload:'Download',navReleases:'Versioni',navTeam:'Team HackerOS',navDocs:'Documentazione'},
    ru:{pageTitle:'HackerOS - Команда',sectionH1:'Команда HackerOS',member0Role:'Основатель HackerOS',footerCopy:'© 2026 HackerOS. Все права защищены.',navHome:'Главная',navDownload:'Скачать',navReleases:'Релизы',navTeam:'Команда HackerOS',navDocs:'Документация'},
    uk:{pageTitle:'HackerOS - Команда',sectionH1:'Команда HackerOS',member0Role:'Засновник HackerOS',footerCopy:'© 2026 HackerOS. Усі права захищені.',navHome:'Головна',navDownload:'Завантажити',navReleases:'Релізи',navTeam:'Команда HackerOS',navDocs:'Документація'},
    zh:{pageTitle:'HackerOS - 团队',sectionH1:'HackerOS 团队',member0Role:'HackerOS 创始人',footerCopy:'© 2026 HackerOS. 保留所有权利。',navHome:'主页',navDownload:'下载',navReleases:'版本',navTeam:'HackerOS 团队',navDocs:'文档'},
    ja:{pageTitle:'HackerOS - チーム',sectionH1:'HackerOS チーム',member0Role:'HackerOS 創設者',footerCopy:'© 2026 HackerOS. 全著作権所有。',navHome:'ホーム',navDownload:'ダウンロード',navReleases:'リリース',navTeam:'HackerOS チーム',navDocs:'ドキュメント'},
};
