(function () {
    const VERSION = "HackerOS V3.0";
    const DATA = {
        pl: { version: VERSION, desc: "Najnowsza główna wersja z znacznymi ulepszeniami: zmieniono z jądra xanmod na xanmod lts (lepsza obsługa urządzeń).", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["Zaktualizowano bazę do najnowszego Debian Testing.", "Poprawiono wsparcie dla sterowników Nvidia dla lepszej wydajności w grach.", "Dodano zaawansowane narzędzia cybersecurity, takie jak ulepszone firewalle i wykrywanie intruzów.", "Poprawki błędów, dodano i ulepszono narzędzia cli oraz gry hackeros.", "Poprawki błędów i ulepszenia stabilności na podstawie opinii użytkowników."] },
        en: { version: VERSION, desc: "Latest major version with significant improvements: changed kernel from xanmod to xanmod lts (better device support).", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["Updated base to the latest Debian Testing.", "Improved Nvidia driver support for better gaming performance.", "Added advanced cybersecurity tools such as improved firewalls and intrusion detection.", "Bug fixes, added and improved cli tools and hackeros games.", "Bug fixes and stability improvements based on user feedback."] },
        de: { version: VERSION, desc: "Neueste Hauptversion mit bedeutenden Verbesserungen: Kernel von XanMod auf XanMod LTS gewechselt (bessere Geräteunterstützung).", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["Basis auf das neueste Debian Testing aktualisiert.", "Verbesserte NVIDIA-Treiberunterstützung für bessere Gaming-Leistung.", "Fortgeschrittene Cybersecurity-Tools hinzugefügt, etwa verbesserte Firewalls und Intrusion Detection.", "Fehlerbehebungen, CLI-Tools und HackerOS-Spiele hinzugefügt und verbessert.", "Fehlerbehebungen und Stabilitätsverbesserungen basierend auf Nutzer-Feedback."] },
        fr: { version: VERSION, desc: "Dernière version majeure avec des améliorations significatives : passage du noyau de XanMod à XanMod LTS (meilleure prise en charge du matériel).", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["Mise à jour de la base vers la dernière version de Debian Testing.", "Amélioration du support des pilotes NVIDIA pour de meilleures performances en jeu.", "Ajout d'outils de cybersécurité avancés tels que des pare-feux améliorés et la détection d'intrusion.", "Corrections de bogues, ajout et amélioration des outils CLI et des jeux HackerOS.", "Corrections de bogues et améliorations de stabilité basées sur les retours des utilisateurs."] },
        es: { version: VERSION, desc: "Última versión mayor con mejoras significativas: cambio del kernel de XanMod a XanMod LTS (mejor soporte de dispositivos).", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["Actualizada la base a la última versión de Debian Testing.", "Mejorado el soporte de controladores NVIDIA para un mejor rendimiento en juegos.", "Añadidas herramientas avanzadas de ciberseguridad, como firewalls mejorados y detección de intrusiones.", "Correcciones de errores, herramientas CLI y juegos de HackerOS añadidos y mejorados.", "Correcciones de errores y mejoras de estabilidad basadas en los comentarios de los usuarios."] },
        it: { version: VERSION, desc: "Ultima versione principale con miglioramenti significativi: passaggio del kernel da XanMod a XanMod LTS (miglior supporto hardware).", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["Aggiornata la base all'ultima versione di Debian Testing.", "Migliorato il supporto ai driver NVIDIA per prestazioni di gioco migliori.", "Aggiunti strumenti avanzati di cybersecurity, come firewall migliorati e rilevamento delle intrusioni.", "Correzioni di bug, strumenti CLI e giochi HackerOS aggiunti e migliorati.", "Correzioni di bug e miglioramenti della stabilità basati sui feedback degli utenti."] },
        ru: { version: VERSION, desc: "Последняя крупная версия со значительными улучшениями: ядро изменено с XanMod на XanMod LTS (лучшая поддержка устройств).", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["База обновлена до последней версии Debian Testing.", "Улучшена поддержка драйверов NVIDIA для лучшей игровой производительности.", "Добавлены продвинутые инструменты кибербезопасности, такие как улучшенные файрволы и обнаружение вторжений.", "Исправления ошибок, добавлены и улучшены CLI-инструменты и игры HackerOS.", "Исправления ошибок и улучшения стабильности на основе отзывов пользователей."] },
        uk: { version: VERSION, desc: "Остання велика версія зі значними покращеннями: ядро змінено з XanMod на XanMod LTS (краща підтримка пристроїв).", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["Базу оновлено до найновішої версії Debian Testing.", "Покращено підтримку драйверів NVIDIA для кращої ігрової продуктивності.", "Додано розширені інструменти кібербезпеки, як-от покращені файрволи та виявлення вторгнень.", "Виправлення помилок, додано та покращено CLI-інструменти та ігри HackerOS.", "Виправлення помилок і покращення стабільності на основі відгуків користувачів."] },
        zh: { version: VERSION, desc: "带来重大改进的最新主要版本：内核由 XanMod 更换为 XanMod LTS（更好的设备支持）。", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["将基础系统更新为最新的 Debian Testing。", "改进了 NVIDIA 驱动支持，带来更好的游戏性能。", "新增了高级网络安全工具，例如改进的防火墙和入侵检测。", "修复了错误，新增并改进了 CLI 工具及 HackerOS 游戏。", "根据用户反馈进行了错误修复和稳定性改进。"] },
        ja: { version: VERSION, desc: "大幅な改善を含む最新のメジャーバージョン：カーネルを XanMod から XanMod LTS に変更（デバイスサポートの向上）。", dates: ["HackerOS Official: 13.09.2025", "HackerOS Nvidia: 13.09.2025", "HackerOS Cybersecurity: 13.09.2025"], changelog: ["ベースを最新の Debian Testing に更新しました。", "NVIDIA ドライバーのサポートを改善し、ゲーム性能を向上させました。", "改善されたファイアウォールや侵入検知など、高度なサイバーセキュリティツールを追加しました。", "不具合を修正し、CLIツールと HackerOS ゲームを追加・改善しました。", "ユーザーからのフィードバックに基づき、不具合修正と安定性の改善を行いました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
