(function () {
    const VERSION = "HackerOS V3.1";
    const DATA = {
        pl: { version: VERSION, desc: "Najnowsza wersja, poprawiono wiele znanych błędów z HackerOS V3.0.", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["Zaktualizowana baza do najnowszego Debian Testing.", "Naprawiono błędy z tapetami.", "Naprawiono błędy z jądrem.", "Dodano nową grę The Racer i nową aplikację HackerOS Welcome."] },
        en: { version: VERSION, desc: "Latest version, fixed many known bugs from HackerOS V3.0.", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["Updated base to the latest Debian Testing.", "Fixed wallpaper bugs.", "Fixed kernel bugs.", "Added new game The Racer and new HackerOS Welcome application."] },
        de: { version: VERSION, desc: "Neueste Version, behebt viele bekannte Fehler aus HackerOS V3.0.", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["Basis auf das neueste Debian Testing aktualisiert.", "Fehler bei Hintergrundbildern behoben.", "Kernel-Fehler behoben.", "Neues Spiel The Racer und neue Anwendung HackerOS Welcome hinzugefügt."] },
        fr: { version: VERSION, desc: "Dernière version, corrigeant de nombreux bogues connus de HackerOS V3.0.", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["Mise à jour de la base vers la dernière version de Debian Testing.", "Correction de bogues liés aux fonds d'écran.", "Correction de bogues du noyau.", "Ajout du nouveau jeu The Racer et de la nouvelle application HackerOS Welcome."] },
        es: { version: VERSION, desc: "Última versión, corrige muchos errores conocidos de HackerOS V3.0.", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["Actualizada la base a la última versión de Debian Testing.", "Corregidos errores de fondos de pantalla.", "Corregidos errores del kernel.", "Añadido el nuevo juego The Racer y la nueva aplicación HackerOS Welcome."] },
        it: { version: VERSION, desc: "Ultima versione, corregge molti bug noti di HackerOS V3.0.", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["Aggiornata la base all'ultima versione di Debian Testing.", "Corretti bug relativi agli sfondi.", "Corretti bug del kernel.", "Aggiunto il nuovo gioco The Racer e la nuova applicazione HackerOS Welcome."] },
        ru: { version: VERSION, desc: "Последняя версия, исправляющая множество известных ошибок HackerOS V3.0.", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["База обновлена до последней версии Debian Testing.", "Исправлены ошибки обоев.", "Исправлены ошибки ядра.", "Добавлена новая игра The Racer и новое приложение HackerOS Welcome."] },
        uk: { version: VERSION, desc: "Найновіша версія, яка виправляє багато відомих помилок HackerOS V3.0.", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["Базу оновлено до найновішої версії Debian Testing.", "Виправлено помилки шпалер.", "Виправлено помилки ядра.", "Додано нову гру The Racer та новий застосунок HackerOS Welcome."] },
        zh: { version: VERSION, desc: "最新版本，修复了 HackerOS V3.0 中许多已知的错误。", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["将基础系统更新为最新的 Debian Testing。", "修复了壁纸相关错误。", "修复了内核相关错误。", "新增了游戏 The Racer 以及新的 HackerOS Welcome 应用。"] },
        ja: { version: VERSION, desc: "HackerOS V3.0 の多くの既知の不具合を修正した最新バージョン。", dates: ["HackerOS Official: 20.09.2025", "HackerOS Cybersecurity: 20.09.2025"], changelog: ["ベースを最新の Debian Testing に更新しました。", "壁紙の不具合を修正しました。", "カーネルの不具合を修正しました。", "新しいゲーム The Racer と新しい HackerOS Welcome アプリケーションを追加しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
