(function () {
    const VERSION = "HackerOS V3.3";
    const DATA = {
        pl: { version: VERSION, desc: "Dodano nową edycję Nvidia.", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["Zaktualizowano bazę do najnowszego Debiana.", "Rozbudowano Hacker Launcher, gotowy do uruchamiania gier i plików .exe.", "Naprawiono i przebudowano Hacker Mode.", "Zaktualizowano skrypty."] },
        en: { version: VERSION, desc: "Added new Nvidia edition.", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["Updated base to the latest Debian.", "Expanded Hacker Launcher, ready to run games and .exe files.", "Fixed and rebuilt Hacker Mode.", "Updated scripts."] },
        de: { version: VERSION, desc: "Neue NVIDIA-Edition hinzugefügt.", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["Basis auf das neueste Debian aktualisiert.", "Hacker Launcher erweitert, bereit zum Ausführen von Spielen und .exe-Dateien.", "Hacker Mode behoben und neu aufgebaut.", "Skripte aktualisiert."] },
        fr: { version: VERSION, desc: "Ajout de la nouvelle édition NVIDIA.", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["Mise à jour de la base vers la dernière version de Debian.", "Extension de Hacker Launcher, prêt à exécuter des jeux et des fichiers .exe.", "Correction et reconstruction de Hacker Mode.", "Mise à jour des scripts."] },
        es: { version: VERSION, desc: "Añadida la nueva edición NVIDIA.", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["Actualizada la base a la última versión de Debian.", "Ampliado Hacker Launcher, listo para ejecutar juegos y archivos .exe.", "Corregido y reconstruido Hacker Mode.", "Actualizados los scripts."] },
        it: { version: VERSION, desc: "Aggiunta la nuova edizione NVIDIA.", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["Aggiornata la base all'ultima versione di Debian.", "Esteso Hacker Launcher, pronto per eseguire giochi e file .exe.", "Corretto e ricostruito Hacker Mode.", "Aggiornati gli script."] },
        ru: { version: VERSION, desc: "Добавлена новая редакция NVIDIA.", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["База обновлена до последней версии Debian.", "Расширен Hacker Launcher, готов к запуску игр и файлов .exe.", "Hacker Mode исправлен и пересобран.", "Обновлены скрипты."] },
        uk: { version: VERSION, desc: "Додано нове видання NVIDIA.", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["Базу оновлено до найновішої версії Debian.", "Розширено Hacker Launcher, готовий до запуску ігор і файлів .exe.", "Hacker Mode виправлено та перезібрано.", "Оновлено скрипти."] },
        zh: { version: VERSION, desc: "新增了 NVIDIA 版本。", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["将基础系统更新为最新的 Debian。", "扩展了 Hacker Launcher，现已支持运行游戏和 .exe 文件。", "修复并重构了 Hacker Mode。", "更新了脚本。"] },
        ja: { version: VERSION, desc: "新しい NVIDIA エディションを追加しました。", dates: ["HackerOS Official: 14.10.2025", "HackerOS Hydra: 14.10.2025", "HackerOS Cybersecurity: 14.10.2025", "HackerOS Nvidia: 14.10.2025"], changelog: ["ベースを最新の Debian に更新しました。", "Hacker Launcher を拡張し、ゲームや .exe ファイルの実行に対応しました。", "Hacker Mode を修正し、再構築しました。", "スクリプトを更新しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
