(function () {
    const VERSION = "HackerOS V3.4";
    const DATA = {
        pl: { version: VERSION, desc: "Usunięto edycję Nvidia, wiele zmian.", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["Usunięto narzędzie hacker-update", "Od teraz nie będzie wbudowanego jądra xanmod, zainstaluj je i ustaw jako domyślne za pomocą polecenia set-xanmod-default", "Rozbudowano narzędzie hacker", "Usunięto gry HackerOS, dodano jedną aplikację która uruchamia wszystkie gry HackerOS", "Od teraz hacker mode nie będzie odpalał za pomocą gamescope tylko cage", "Dodano aplikację inspirowaną ASUS Armoury Crate o nazwie HackerOS Game Mode"] },
        en: { version: VERSION, desc: "Removed Nvidia edition, many changes.", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["Removed hacker-update tool", "From now on, there will be no built-in xanmod kernel, install it and set as default using set-xanmod-default command", "Expanded hacker tool", "Removed HackerOS games, added one application that launches all HackerOS games", "From now on, hacker mode will not use gamescope but cage", "Added application inspired by ASUS Armoury Crate called HackerOS Game Mode"] },
        de: { version: VERSION, desc: "NVIDIA-Edition entfernt, zahlreiche Änderungen.", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["Das Tool hacker-update entfernt.", "Ab sofort gibt es keinen integrierten XanMod-Kernel mehr – installiere ihn und setze ihn mit dem Befehl set-xanmod-default als Standard.", "Das Tool hacker erweitert.", "HackerOS-Spiele entfernt, stattdessen eine Anwendung hinzugefügt, die alle HackerOS-Spiele startet.", "Der Hacker-Modus nutzt ab sofort nicht mehr Gamescope, sondern Cage.", "Eine von ASUS Armoury Crate inspirierte Anwendung namens HackerOS Game Mode hinzugefügt."] },
        fr: { version: VERSION, desc: "Suppression de l'édition NVIDIA, nombreux changements.", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["Suppression de l'outil hacker-update.", "Désormais, il n'y a plus de noyau XanMod intégré par défaut ; installez-le et définissez-le par défaut avec la commande set-xanmod-default.", "Extension de l'outil hacker.", "Suppression des jeux HackerOS, ajout d'une application unique lançant tous les jeux HackerOS.", "Désormais, le mode hacker utilise Cage au lieu de Gamescope.", "Ajout d'une application inspirée d'ASUS Armoury Crate, nommée HackerOS Game Mode."] },
        es: { version: VERSION, desc: "Eliminada la edición NVIDIA, numerosos cambios.", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["Eliminada la herramienta hacker-update.", "A partir de ahora no habrá un kernel XanMod integrado; instálalo y establécelo por defecto con el comando set-xanmod-default.", "Ampliada la herramienta hacker.", "Eliminados los juegos de HackerOS, añadida una aplicación que los lanza todos.", "A partir de ahora, el modo hacker usará Cage en lugar de Gamescope.", "Añadida una aplicación inspirada en ASUS Armoury Crate llamada HackerOS Game Mode."] },
        it: { version: VERSION, desc: "Rimossa l'edizione NVIDIA, numerose modifiche.", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["Rimosso lo strumento hacker-update.", "D'ora in poi non ci sarà più un kernel XanMod integrato: installalo e impostalo come predefinito con il comando set-xanmod-default.", "Esteso lo strumento hacker.", "Rimossi i giochi HackerOS, aggiunta un'unica applicazione che li avvia tutti.", "D'ora in poi la modalità hacker userà Cage al posto di Gamescope.", "Aggiunta un'applicazione ispirata ad ASUS Armoury Crate chiamata HackerOS Game Mode."] },
        ru: { version: VERSION, desc: "Удалена редакция NVIDIA, множество изменений.", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["Удалён инструмент hacker-update.", "Отныне встроенного ядра XanMod больше нет — установите его и сделайте ядром по умолчанию командой set-xanmod-default.", "Расширен инструмент hacker.", "Удалены игры HackerOS, добавлено единое приложение для запуска всех игр HackerOS.", "Отныне режим hacker использует Cage вместо Gamescope.", "Добавлено приложение, вдохновлённое ASUS Armoury Crate, под названием HackerOS Game Mode."] },
        uk: { version: VERSION, desc: "Видалено видання NVIDIA, численні зміни.", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["Видалено інструмент hacker-update.", "Відтепер вбудованого ядра XanMod більше немає — встановіть його та зробіть типовим за допомогою команди set-xanmod-default.", "Розширено інструмент hacker.", "Видалено ігри HackerOS, додано єдиний застосунок для запуску всіх ігор HackerOS.", "Відтепер режим hacker використовує Cage замість Gamescope.", "Додано застосунок, натхненний ASUS Armoury Crate, під назвою HackerOS Game Mode."] },
        zh: { version: VERSION, desc: "移除了 NVIDIA 版本，进行了大量变更。", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["移除了 hacker-update 工具。", "自此不再内置 XanMod 内核 —— 请自行安装，并使用 set-xanmod-default 命令将其设为默认内核。", "扩展了 hacker 工具。", "移除了 HackerOS 自带游戏，改为新增一个可启动所有 HackerOS 游戏的应用。", "自此 hacker 模式将不再使用 Gamescope，而是使用 Cage。", "新增了一款受 ASUS Armoury Crate 启发的应用，名为 HackerOS Game Mode。"] },
        ja: { version: VERSION, desc: "NVIDIA エディションを削除し、多数の変更を行いました。", dates: ["HackerOS Official: 24.10.2025", "HackerOS Hydra: 24.10.2025", "HackerOS Cybersecurity: 24.10.2025"], changelog: ["hacker-update ツールを削除しました。", "今後は XanMod カーネルが標準搭載されなくなります。set-xanmod-default コマンドでインストールしデフォルトに設定してください。", "hacker ツールを拡張しました。", "HackerOS のゲームを削除し、代わりにすべての HackerOS ゲームを起動する単一のアプリケーションを追加しました。", "今後 hacker モードは Gamescope ではなく Cage を使用します。", "ASUS Armoury Crate にインスパイアされた HackerOS Game Mode というアプリケーションを追加しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
