(function () {
    const VERSION = "HackerOS V3.5";
    const DATA = {
        pl: { version: VERSION, desc: "Nowa wersja z aktualizacją bazy, dodanym językiem programowania hacker lang oraz innymi zmianami.", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["Zaktualizowano bazę do najnowszego Debiana", "Dodano język programowania hacker lang", "Zaktualizowano hacker mode aby działał tylko i wyłącznie na x11 (hacker mode będzie działać zarówno na nowych gpu jak i na starych)", "Zaktualizowano permisje dla plików"] },
        en: { version: VERSION, desc: "New version with base update, added hacker lang programming language and other changes.", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["Updated base to the latest Debian", "Added hacker lang programming language", "Updated hacker mode to work only on x11 (hacker mode will work on both new and old GPUs)", "Updated file permissions"] },
        de: { version: VERSION, desc: "Neue Version mit Basisaktualisierung, Einführung der Programmiersprache Hacker Lang und weiteren Änderungen.", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["Basis auf das neueste Debian aktualisiert.", "Programmiersprache Hacker Lang hinzugefügt.", "Hacker-Modus aktualisiert, läuft nun ausschließlich unter X11 (funktioniert sowohl mit neuen als auch alten GPUs).", "Dateiberechtigungen aktualisiert."] },
        fr: { version: VERSION, desc: "Nouvelle version avec mise à jour de la base, ajout du langage de programmation Hacker Lang et autres changements.", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["Mise à jour de la base vers la dernière version de Debian.", "Ajout du langage de programmation Hacker Lang.", "Mise à jour du mode hacker pour fonctionner uniquement sous X11 (fonctionne sur les GPU récents comme anciens).", "Mise à jour des permissions de fichiers."] },
        es: { version: VERSION, desc: "Nueva versión con actualización de la base, incorporación del lenguaje de programación Hacker Lang y otros cambios.", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["Actualizada la base a la última versión de Debian.", "Añadido el lenguaje de programación Hacker Lang.", "Actualizado el modo hacker para funcionar únicamente en X11 (funciona tanto en GPU nuevas como antiguas).", "Actualizados los permisos de archivos."] },
        it: { version: VERSION, desc: "Nuova versione con aggiornamento della base, introduzione del linguaggio di programmazione Hacker Lang e altre modifiche.", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["Aggiornata la base all'ultima versione di Debian.", "Aggiunto il linguaggio di programmazione Hacker Lang.", "Aggiornata la modalità hacker per funzionare solo su X11 (funziona sia su GPU nuove che vecchie).", "Aggiornati i permessi dei file."] },
        ru: { version: VERSION, desc: "Новая версия с обновлением базы, добавлением языка программирования Hacker Lang и другими изменениями.", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["База обновлена до последней версии Debian.", "Добавлен язык программирования Hacker Lang.", "Режим hacker обновлён и теперь работает только на X11 (работает как на новых, так и на старых GPU).", "Обновлены права доступа к файлам."] },
        uk: { version: VERSION, desc: "Нова версія з оновленням бази, додаванням мови програмування Hacker Lang та іншими змінами.", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["Базу оновлено до найновішої версії Debian.", "Додано мову програмування Hacker Lang.", "Режим hacker оновлено, тепер працює лише на X11 (працює як на нових, так і на старих GPU).", "Оновлено права доступу до файлів."] },
        zh: { version: VERSION, desc: "带来基础系统更新、加入 Hacker Lang 编程语言及其他变更的新版本。", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["将基础系统更新为最新的 Debian。", "新增了 Hacker Lang 编程语言。", "更新了 hacker 模式，使其仅在 X11 上运行（新旧 GPU 均可使用）。", "更新了文件权限。"] },
        ja: { version: VERSION, desc: "ベースの更新、Hacker Lang プログラミング言語の追加、その他の変更を含む新しいバージョン。", dates: ["HackerOS Official: 29.10.2025", "HackerOS Hydra: 29.10.2025", "HackerOS Cybersecurity: 29.10.2025"], changelog: ["ベースを最新の Debian に更新しました。", "Hacker Lang プログラミング言語を追加しました。", "hacker モードを更新し、X11 上でのみ動作するようにしました（新旧どちらのGPUでも動作します）。", "ファイルの権限を更新しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
