(function () {
    const VERSION = "HackerOS V3.6";
    const DATA = {
        pl: { version: VERSION, desc: "Nowa wersja z naprawionymi błędami i modyfikacjami", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["Zaktualizowano bazę do najnowszego Debiana", "Naprawiono błędy w aplikacji hacker launcher", "Naprawiono błędy w hacker mode", "Naprawiono/Rozbudowano skrypty"] },
        en: { version: VERSION, desc: "New version with bug fixes and modifications.", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["Updated base to the latest Debian", "Fixed bugs in hacker launcher application", "Fixed bugs in hacker mode", "Fixed/Expanded scripts"] },
        de: { version: VERSION, desc: "Neue Version mit Fehlerbehebungen und Anpassungen.", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["Basis auf das neueste Debian aktualisiert.", "Fehler in der Hacker-Launcher-Anwendung behoben.", "Fehler im Hacker-Modus behoben.", "Skripte behoben/erweitert."] },
        fr: { version: VERSION, desc: "Nouvelle version avec correctifs de bogues et modifications.", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["Mise à jour de la base vers la dernière version de Debian.", "Correction de bogues dans l'application Hacker Launcher.", "Correction de bogues dans le mode hacker.", "Correction/extension des scripts."] },
        es: { version: VERSION, desc: "Nueva versión con correcciones de errores y modificaciones.", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["Actualizada la base a la última versión de Debian.", "Corregidos errores en la aplicación Hacker Launcher.", "Corregidos errores en el modo hacker.", "Scripts corregidos/ampliados."] },
        it: { version: VERSION, desc: "Nuova versione con correzioni di bug e modifiche.", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["Aggiornata la base all'ultima versione di Debian.", "Corretti bug nell'applicazione Hacker Launcher.", "Corretti bug nella modalità hacker.", "Script corretti/estesi."] },
        ru: { version: VERSION, desc: "Новая версия с исправлениями ошибок и доработками.", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["База обновлена до последней версии Debian.", "Исправлены ошибки в приложении Hacker Launcher.", "Исправлены ошибки в режиме hacker.", "Скрипты исправлены/расширены."] },
        uk: { version: VERSION, desc: "Нова версія з виправленнями помилок і доопрацюваннями.", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["Базу оновлено до найновішої версії Debian.", "Виправлено помилки в застосунку Hacker Launcher.", "Виправлено помилки в режимі hacker.", "Скрипти виправлено/розширено."] },
        zh: { version: VERSION, desc: "带来错误修复和调整的新版本。", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["将基础系统更新为最新的 Debian。", "修复了 Hacker Launcher 应用中的错误。", "修复了 hacker 模式中的错误。", "修复/扩展了脚本。"] },
        ja: { version: VERSION, desc: "不具合修正と調整を含む新しいバージョン。", dates: ["HackerOS Official: 07.11.2025", "HackerOS Hydra: 07.11.2025", "HackerOS Cybersecurity: 07.11.2025"], changelog: ["ベースを最新の Debian に更新しました。", "Hacker Launcher アプリケーションの不具合を修正しました。", "hacker モードの不具合を修正しました。", "スクリプトを修正・拡張しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
