(function () {
    const VERSION = "HackerOS V3.7";
    const DATA = {
        pl: { version: VERSION, desc: "Nowa wersja z naprawionymi skryptami oraz rozbudowanymi narzędziami hacker, hackerc", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["Zaktualizowano bazę do najnowszego Debiana, dodano najnowsze narzędzia: HackerOS Welcome, hacker oraz narzędzia dla języka programowania hacker - hackerc", "Naprawiono skrypty uruchamiające hacker mode"] },
        en: { version: VERSION, desc: "New version with fixed scripts and expanded hacker, hackerc tools.", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["Updated base to the latest Debian, added latest tools: HackerOS Welcome, hacker, and tools for hacker programming language - hackerc", "Fixed scripts launching hacker mode"] },
        de: { version: VERSION, desc: "Neue Version mit behobenen Skripten und erweiterten Tools hacker, hackerc.", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["Basis auf das neueste Debian aktualisiert, neueste Tools hinzugefügt: HackerOS Welcome, hacker sowie Tools für die Programmiersprache hacker – hackerc.", "Skripte zum Starten des Hacker-Modus behoben."] },
        fr: { version: VERSION, desc: "Nouvelle version avec scripts corrigés et outils hacker, hackerc enrichis.", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["Mise à jour de la base vers la dernière version de Debian, ajout des derniers outils : HackerOS Welcome, hacker, ainsi que les outils du langage de programmation hacker – hackerc.", "Correction des scripts de lancement du mode hacker."] },
        es: { version: VERSION, desc: "Nueva versión con scripts corregidos y herramientas hacker, hackerc ampliadas.", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["Actualizada la base a la última versión de Debian, añadidas las últimas herramientas: HackerOS Welcome, hacker y las herramientas del lenguaje de programación hacker – hackerc.", "Corregidos los scripts de inicio del modo hacker."] },
        it: { version: VERSION, desc: "Nuova versione con script corretti e strumenti hacker, hackerc estesi.", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["Aggiornata la base all'ultima versione di Debian, aggiunti gli strumenti più recenti: HackerOS Welcome, hacker e gli strumenti del linguaggio di programmazione hacker – hackerc.", "Corretti gli script di avvio della modalità hacker."] },
        ru: { version: VERSION, desc: "Новая версия с исправленными скриптами и расширенными инструментами hacker, hackerc.", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["База обновлена до последней версии Debian, добавлены новейшие инструменты: HackerOS Welcome, hacker, а также инструменты языка программирования hacker — hackerc.", "Исправлены скрипты запуска режима hacker."] },
        uk: { version: VERSION, desc: "Нова версія з виправленими скриптами та розширеними інструментами hacker, hackerc.", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["Базу оновлено до найновішої версії Debian, додано найновіші інструменти: HackerOS Welcome, hacker, а також інструменти мови програмування hacker — hackerc.", "Виправлено скрипти запуску режиму hacker."] },
        zh: { version: VERSION, desc: "带来修复脚本以及扩展 hacker、hackerc 工具的新版本。", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["将基础系统更新为最新的 Debian，新增了最新工具：HackerOS Welcome、hacker，以及 hacker 编程语言的相关工具 —— hackerc。", "修复了启动 hacker 模式的脚本。"] },
        ja: { version: VERSION, desc: "スクリプトを修正し、hacker・hackerc ツールを拡張した新しいバージョン。", dates: ["HackerOS Official: 10.11.2025", "HackerOS Hydra: 10.11.2025", "HackerOS Cybersecurity: 10.11.2025"], changelog: ["ベースを最新の Debian に更新し、最新ツール（HackerOS Welcome、hacker、hacker プログラミング言語用ツールの hackerc）を追加しました。", "hacker モードを起動するスクリプトを修正しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
