(function () {
    const VERSION = "HackerOS V3.9";
    const DATA = {
        pl: { version: VERSION, desc: "Nowa wersja z rozbudowanymi narzędziami.", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["Zaktualizowano bazę do najnowszego Debiana.", "Rozbudowano skrypty: unpack-xanmod i unpack-liquorix. Rozbudowano narzędzie hacker oraz zaktualizowano aplikację update system."] },
        en: { version: VERSION, desc: "New version with expanded tools.", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["Updated base to the latest Debian.", "Expanded scripts: unpack-xanmod and unpack-liquorix. Expanded hacker tool and updated update system application."] },
        de: { version: VERSION, desc: "Neue Version mit erweiterten Tools.", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["Basis auf das neueste Debian aktualisiert.", "Skripte erweitert: unpack-xanmod und unpack-liquorix. Tool hacker erweitert und die Update-Anwendung aktualisiert."] },
        fr: { version: VERSION, desc: "Nouvelle version avec outils enrichis.", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["Mise à jour de la base vers la dernière version de Debian.", "Extension des scripts unpack-xanmod et unpack-liquorix. Extension de l'outil hacker et mise à jour de l'application de mise à jour du système."] },
        es: { version: VERSION, desc: "Nueva versión con herramientas ampliadas.", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["Actualizada la base a la última versión de Debian.", "Ampliados los scripts unpack-xanmod y unpack-liquorix. Ampliada la herramienta hacker y actualizada la aplicación de actualización del sistema."] },
        it: { version: VERSION, desc: "Nuova versione con strumenti estesi.", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["Aggiornata la base all'ultima versione di Debian.", "Estesi gli script unpack-xanmod e unpack-liquorix. Esteso lo strumento hacker e aggiornata l'applicazione di aggiornamento del sistema."] },
        ru: { version: VERSION, desc: "Новая версия с расширенными инструментами.", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["База обновлена до последней версии Debian.", "Расширены скрипты unpack-xanmod и unpack-liquorix. Расширен инструмент hacker, обновлено приложение системного обновления."] },
        uk: { version: VERSION, desc: "Нова версія з розширеними інструментами.", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["Базу оновлено до найновішої версії Debian.", "Розширено скрипти unpack-xanmod і unpack-liquorix. Розширено інструмент hacker, оновлено застосунок оновлення системи."] },
        zh: { version: VERSION, desc: "带来扩展工具的新版本。", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["将基础系统更新为最新的 Debian。", "扩展了 unpack-xanmod 和 unpack-liquorix 脚本，扩展了 hacker 工具，并更新了系统更新应用。"] },
        ja: { version: VERSION, desc: "ツールを拡張した新しいバージョン。", dates: ["HackerOS Official: 22.11.2025", "HackerOS Hydra: 22.11.2025", "HackerOS Cybersecurity: 23.11.2025"], changelog: ["ベースを最新の Debian に更新しました。", "unpack-xanmod および unpack-liquorix スクリプトを拡張しました。hacker ツールを拡張し、システム更新アプリケーションを更新しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
