(function () {
    const VERSION = "HackerOS V4.0";
    const DATA = {
        pl: { version: VERSION, desc: "Nowa wersja z zaktualizowanymi narzędziami oraz aplikacjami.", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["Zaktualizowano narzędzia hacker, hli, hackerc, bytes, hpm oraz aplikacje", "Dodano MOTD"] },
        en: { version: VERSION, desc: "New version with updated tools and applications.", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["Updated hacker, hli, hackerc, bytes, hpm tools and applications", "Added MOTD"] },
        de: { version: VERSION, desc: "Neue Version mit aktualisierten Tools und Anwendungen.", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["Tools und Anwendungen hacker, hli, hackerc, bytes, hpm aktualisiert.", "MOTD hinzugefügt."] },
        fr: { version: VERSION, desc: "Nouvelle version avec outils et applications mis à jour.", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["Mise à jour des outils et applications hacker, hli, hackerc, bytes, hpm.", "Ajout du MOTD."] },
        es: { version: VERSION, desc: "Nueva versión con herramientas y aplicaciones actualizadas.", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["Actualizadas las herramientas y aplicaciones hacker, hli, hackerc, bytes, hpm.", "Añadido el MOTD."] },
        it: { version: VERSION, desc: "Nuova versione con strumenti e applicazioni aggiornati.", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["Aggiornati gli strumenti e le applicazioni hacker, hli, hackerc, bytes, hpm.", "Aggiunto il MOTD."] },
        ru: { version: VERSION, desc: "Новая версия с обновлёнными инструментами и приложениями.", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["Обновлены инструменты и приложения hacker, hli, hackerc, bytes, hpm.", "Добавлен MOTD."] },
        uk: { version: VERSION, desc: "Нова версія з оновленими інструментами та застосунками.", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["Оновлено інструменти та застосунки hacker, hli, hackerc, bytes, hpm.", "Додано MOTD."] },
        zh: { version: VERSION, desc: "带来更新工具和应用的新版本。", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["更新了 hacker、hli、hackerc、bytes、hpm 等工具和应用。", "新增了 MOTD。"] },
        ja: { version: VERSION, desc: "ツールとアプリケーションを更新した新しいバージョン。", dates: ["HackerOS Official: 8.12.2025", "HackerOS Official Gnome: 12.12.2025", "HackerOS Official Xfce: 12.12.2025", "HackerOS Hydra: 8.12.2025", "HackerOS Cybersecurity: 9.12.2025"], changelog: ["hacker、hli、hackerc、bytes、hpm のツールとアプリケーションを更新しました。", "MOTD を追加しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
