(function () {
    const VERSION = "HackerOS V4.1";
    const DATA = {
        pl: { version: VERSION, desc: "Nowa wersja z naprawionymi błędami i nowymi funkcjami.", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["Naprawiono błędy z MOTD", "Dodano nową edycję LTS", "Zaktualizowano bazę Debiana do Debian Forky", "Dodano zaktualizowane narzędzia"] },
        en: { version: VERSION, desc: "New version with fixed bugs and new features.", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["Fixed MOTD bugs", "Added new LTS edition", "Updated Debian base to Debian Forky", "Added updated tools"] },
        de: { version: VERSION, desc: "Neue Version mit behobenen Fehlern und neuen Funktionen.", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["MOTD-Fehler behoben.", "Neue LTS-Edition hinzugefügt.", "Debian-Basis auf Debian Forky aktualisiert.", "Aktualisierte Tools hinzugefügt."] },
        fr: { version: VERSION, desc: "Nouvelle version avec bogues corrigés et nouvelles fonctionnalités.", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["Correction de bogues du MOTD.", "Ajout de la nouvelle édition LTS.", "Mise à jour de la base Debian vers Debian Forky.", "Ajout d'outils mis à jour."] },
        es: { version: VERSION, desc: "Nueva versión con errores corregidos y nuevas funciones.", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["Corregidos errores del MOTD.", "Añadida la nueva edición LTS.", "Actualizada la base de Debian a Debian Forky.", "Añadidas herramientas actualizadas."] },
        it: { version: VERSION, desc: "Nuova versione con bug corretti e nuove funzionalità.", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["Corretti bug del MOTD.", "Aggiunta la nuova edizione LTS.", "Aggiornata la base Debian a Debian Forky.", "Aggiunti strumenti aggiornati."] },
        ru: { version: VERSION, desc: "Новая версия с исправленными ошибками и новыми функциями.", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["Исправлены ошибки MOTD.", "Добавлена новая редакция LTS.", "База Debian обновлена до Debian Forky.", "Добавлены обновлённые инструменты."] },
        uk: { version: VERSION, desc: "Нова версія з виправленими помилками та новими функціями.", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["Виправлено помилки MOTD.", "Додано нове видання LTS.", "Базу Debian оновлено до Debian Forky.", "Додано оновлені інструменти."] },
        zh: { version: VERSION, desc: "带来错误修复和新功能的新版本。", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["修复了 MOTD 相关错误。", "新增了 LTS 版本。", "将 Debian 基础更新为 Debian Forky。", "新增了更新后的工具。"] },
        ja: { version: VERSION, desc: "不具合修正と新機能を含む新しいバージョン。", dates: ["HackerOS Official: 26.12.2025", "HackerOS Hydra: 26.12.2025", "HackerOS Cybersecurity: 26.12.2026", "HackerOS LTS: 26.12.2025"], changelog: ["MOTD の不具合を修正しました。", "新しい LTS エディションを追加しました。", "Debian のベースを Debian Forky に更新しました。", "更新されたツールを追加しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
