(function () {
    const VERSION = "HackerOS V4.2";
    const DATA = {
        pl: { version: VERSION, desc: "Nowa wersja z zaktualizowanymi narzędziami CLI i nowymi funkcjami.", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["Zaktualizowano narzędzia CLI", "Dodano nową aplikację HackerOS App", "Naprawiono narzędzie CLI o nazwie HackerOS-Steam", "Dodano prerelease dla edycji atomic", "Zaktualizowano edycję cybersecurity o nowe narzędzia i lepszą przeglądarkę"] },
        en: { version: VERSION, desc: "New version with updated CLI tools and new features.", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["Updated CLI tools", "Added new HackerOS App", "Fixed CLI tool named HackerOS-Steam", "Added prerelease for atomic edition", "Updated cybersecurity edition with new tools and better browser"] },
        de: { version: VERSION, desc: "Neue Version mit aktualisierten CLI-Tools und neuen Funktionen.", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["CLI-Tools aktualisiert.", "Neue HackerOS-App hinzugefügt.", "Fehler im CLI-Tool HackerOS-Steam behoben.", "Pre-Release für die Atomic-Edition hinzugefügt.", "Cybersecurity-Edition mit neuen Tools und besserem Browser aktualisiert."] },
        fr: { version: VERSION, desc: "Nouvelle version avec outils CLI mis à jour et nouvelles fonctionnalités.", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["Mise à jour des outils CLI.", "Ajout de la nouvelle application HackerOS.", "Correction de l'outil CLI nommé HackerOS-Steam.", "Ajout d'une pré-version pour l'édition Atomic.", "Mise à jour de l'édition cybersécurité avec de nouveaux outils et un meilleur navigateur."] },
        es: { version: VERSION, desc: "Nueva versión con herramientas CLI actualizadas y nuevas funciones.", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["Actualizadas las herramientas CLI.", "Añadida la nueva aplicación HackerOS.", "Corregida la herramienta CLI llamada HackerOS-Steam.", "Añadida versión preliminar para la edición Atomic.", "Actualizada la edición de ciberseguridad con nuevas herramientas y un mejor navegador."] },
        it: { version: VERSION, desc: "Nuova versione con strumenti CLI aggiornati e nuove funzionalità.", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["Aggiornati gli strumenti CLI.", "Aggiunta la nuova app HackerOS.", "Corretto lo strumento CLI chiamato HackerOS-Steam.", "Aggiunta una pre-release per l'edizione Atomic.", "Aggiornata l'edizione cybersecurity con nuovi strumenti e un browser migliore."] },
        ru: { version: VERSION, desc: "Новая версия с обновлёнными CLI-инструментами и новыми функциями.", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["Обновлены CLI-инструменты.", "Добавлено новое приложение HackerOS.", "Исправлен CLI-инструмент HackerOS-Steam.", "Добавлен пре-релиз для редакции Atomic.", "Обновлена редакция Cybersecurity с новыми инструментами и улучшенным браузером."] },
        uk: { version: VERSION, desc: "Нова версія з оновленими CLI-інструментами та новими функціями.", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["Оновлено CLI-інструменти.", "Додано новий застосунок HackerOS.", "Виправлено CLI-інструмент HackerOS-Steam.", "Додано пре-реліз для видання Atomic.", "Оновлено видання Cybersecurity новими інструментами та кращим браузером."] },
        zh: { version: VERSION, desc: "带来更新的 CLI 工具和新功能的新版本。", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["更新了 CLI 工具。", "新增了 HackerOS 应用。", "修复了名为 HackerOS-Steam 的 CLI 工具。", "为 Atomic 版本新增了预发布版。", "为 Cybersecurity 版本更新了新工具和更好的浏览器。"] },
        ja: { version: VERSION, desc: "CLIツールの更新と新機能を含む新しいバージョン。", dates: ["HackerOS Official: 18.01.2026", "HackerOS Cybersecurity: 18.01.2026"], changelog: ["CLIツールを更新しました。", "新しい HackerOS アプリを追加しました。", "CLIツール HackerOS-Steam の不具合を修正しました。", "Atomic エディションのプレリリースを追加しました。", "Cybersecurity エディションを新しいツールとより良いブラウザで更新しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
