(function () {
    const VERSION = "HackerOS V4.3";
    const DATA = {
        pl: { version: VERSION, desc: "Nowa wersja z zaktualizowaną edycją cybersecurity oraz narzędziami GUI.", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["Zaktualizowano narzędzia CLI", "Zaktualizowano narzędzia GUI", "Nowy prerelease dla edycji atomic", "Dodano nową edycję NVIDIA"] },
        en: { version: VERSION, desc: "New version with updated cybersecurity edition and GUI tools.", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["Updated CLI tools", "Updated GUI tools", "New prerelease for atomic edition", "Added new NVIDIA edition"] },
        de: { version: VERSION, desc: "Neue Version mit aktualisierter Cybersecurity-Edition und GUI-Tools.", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["CLI-Tools aktualisiert.", "GUI-Tools aktualisiert.", "Neues Pre-Release für die Atomic-Edition.", "Neue NVIDIA-Edition hinzugefügt."] },
        fr: { version: VERSION, desc: "Nouvelle version avec édition cybersécurité mise à jour et outils GUI.", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["Mise à jour des outils CLI.", "Mise à jour des outils GUI.", "Nouvelle pré-version pour l'édition Atomic.", "Ajout de la nouvelle édition NVIDIA."] },
        es: { version: VERSION, desc: "Nueva versión con edición de ciberseguridad y herramientas GUI actualizadas.", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["Actualizadas las herramientas CLI.", "Actualizadas las herramientas GUI.", "Nueva versión preliminar para la edición Atomic.", "Añadida la nueva edición NVIDIA."] },
        it: { version: VERSION, desc: "Nuova versione con edizione cybersecurity aggiornata e strumenti GUI.", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["Aggiornati gli strumenti CLI.", "Aggiornati gli strumenti GUI.", "Nuova pre-release per l'edizione Atomic.", "Aggiunta la nuova edizione NVIDIA."] },
        ru: { version: VERSION, desc: "Новая версия с обновлённой редакцией Cybersecurity и GUI-инструментами.", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["Обновлены CLI-инструменты.", "Обновлены GUI-инструменты.", "Новый пре-релиз для редакции Atomic.", "Добавлена новая редакция NVIDIA."] },
        uk: { version: VERSION, desc: "Нова версія з оновленим виданням Cybersecurity та GUI-інструментами.", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["Оновлено CLI-інструменти.", "Оновлено GUI-інструменти.", "Новий пре-реліз для видання Atomic.", "Додано нове видання NVIDIA."] },
        zh: { version: VERSION, desc: "带来更新的 Cybersecurity 版本与 GUI 工具的新版本。", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["更新了 CLI 工具。", "更新了 GUI 工具。", "为 Atomic 版本发布了新的预发布版。", "新增了 NVIDIA 版本。"] },
        ja: { version: VERSION, desc: "Cybersecurity エディションと GUI ツールを更新した新しいバージョン。", dates: ["HackerOS Official: 6.02.2026", "HackerOS Cybersecurity: 7.02.2026", "HackerOS NVIDIA: 7.02.2026"], changelog: ["CLIツールを更新しました。", "GUIツールを更新しました。", "Atomic エディションの新しいプレリリースを公開しました。", "新しい NVIDIA エディションを追加しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
