(function () {
    const VERSION = "HackerOS V4.5";
    const DATA = {
        pl: { version: VERSION, desc: "Nowa edycja głównie z poprawą narzędzi.", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["Naprawiono błędy w narzędziach: HackerOS-Steam, hacker", "Zaktualizowano narzędzia CLI", "Dodano obsluge kilku języków (domyślnie polski ale można zmienić) dla narzędzia hacker", "Zaktualizowano motd"] },
        en: { version: VERSION, desc: "New edition mainly with tool improvements.", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["Fixed bugs in tools: HackerOS-Steam, hacker", "Updated CLI tools", "Added multi-language support (default Polish, can be changed) for hacker tool", "Updated MOTD"] },
        de: { version: VERSION, desc: "Neue Edition, hauptsächlich mit Tool-Verbesserungen.", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["Fehler in den Tools HackerOS-Steam und hacker behoben.", "CLI-Tools aktualisiert.", "Mehrsprachige Unterstützung für das Tool hacker hinzugefügt (Standard Polnisch, änderbar).", "MOTD aktualisiert."] },
        fr: { version: VERSION, desc: "Nouvelle édition axée principalement sur les améliorations des outils.", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["Correction de bogues dans les outils HackerOS-Steam et hacker.", "Mise à jour des outils CLI.", "Ajout du support multilingue (polonais par défaut, modifiable) pour l'outil hacker.", "Mise à jour du MOTD."] },
        es: { version: VERSION, desc: "Nueva edición centrada principalmente en mejoras de herramientas.", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["Corregidos errores en las herramientas HackerOS-Steam y hacker.", "Actualizadas las herramientas CLI.", "Añadido soporte multilingüe (polaco por defecto, configurable) para la herramienta hacker.", "Actualizado el MOTD."] },
        it: { version: VERSION, desc: "Nuova edizione incentrata principalmente sui miglioramenti degli strumenti.", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["Corretti bug negli strumenti HackerOS-Steam e hacker.", "Aggiornati gli strumenti CLI.", "Aggiunto il supporto multilingua (polacco predefinito, modificabile) per lo strumento hacker.", "Aggiornato il MOTD."] },
        ru: { version: VERSION, desc: "Новая версия, в основном с улучшениями инструментов.", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["Исправлены ошибки в инструментах HackerOS-Steam и hacker.", "Обновлены CLI-инструменты.", "Добавлена поддержка нескольких языков (по умолчанию польский, можно изменить) для инструмента hacker.", "Обновлён MOTD."] },
        uk: { version: VERSION, desc: "Нове видання, переважно з покращеннями інструментів.", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["Виправлено помилки в інструментах HackerOS-Steam і hacker.", "Оновлено CLI-інструменти.", "Додано багатомовну підтримку (за замовчуванням польська, можна змінити) для інструмента hacker.", "Оновлено MOTD."] },
        zh: { version: VERSION, desc: "主要带来工具改进的新版本。", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["修复了 HackerOS-Steam 和 hacker 工具中的错误。", "更新了 CLI 工具。", "为 hacker 工具新增了多语言支持（默认波兰语，可更改）。", "更新了 MOTD。"] },
        ja: { version: VERSION, desc: "主にツールの改善を含む新しいエディション。", dates: ["HackerOS Official: 6.04.2026", "HackerOS NVIDIA: 5.04.2026", "HackerOS Cybersecurity: 4.04.2026", "HackerOS Gnome: 4.04.2026", "HackerOS Hydra: 3.04.2026", "HackerOS Xfce: 3.04.2026"], changelog: ["HackerOS-Steam および hacker ツールの不具合を修正しました。", "CLIツールを更新しました。", "hacker ツールに多言語サポート（デフォルトはポーランド語、変更可能）を追加しました。", "MOTD を更新しました。"] },
    };

    window.HACKEROS_RELEASES_REGISTRY = window.HACKEROS_RELEASES_REGISTRY || [];
    window.HACKEROS_RELEASES_REGISTRY.push({ version: VERSION, data: DATA });
})();
